name: agenda_calendar_infinite
description: "A Flutter calendar widget library with infinite scroll support, including vertical calendar and horizontal Gantt chart components."
version: 0.1.0
homepage: https://github.com/lyj-514328/agenda_calendar_infinite
repository: https://github.com/lyj-514328/agenda_calendar_infinite

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
